version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    ports:
      - 5532:5432
    volumes:
      - type: bind
        source: /c/tmp/volume/data
        target: /etc/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - PGDATA=/etc/data
  